okulbilisim_cms_post_admin:
    resource: "@OkulbilisimCmsBundle/Resources/config/routing/post.yml"
    prefix:   /admin/post
okulbilisim_cms_post_detail:
    pattern: /{pageType}/{slug}
    defaults: { _controller: OkulbilisimCmsBundle:Post:detail }