
okulbilisim_cms_admin:
    path:     /cms/post/{posttype}/{object}/{id}
    defaults: { _controller: OkulbilisimCmsBundle:Admin:index, posttype: 'default' }
okulbilisim_cms_post_admin:
    resource: "@OkulbilisimCmsBundle/Resources/config/routing/post.yml"
    prefix:   /cms/post
okulbilisim_cms_post_detail:
    path:     /cms/{pageType}/{slug}
    defaults: { _controller: OkulbilisimCmsBundle:Post:detail }