post:
    path:     /
    defaults: { _controller: "OkulbilisimCmsBundle:Post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "OkulbilisimCmsBundle:Post:show" }

post_new:
    path:     /new/{object}/{objectId}/{parentPost}
    defaults: { _controller: "OkulbilisimCmsBundle:Post:new" , object: null, objectId: 0,parentPost: 0}
post_create:
    path:     /create/{object}/{objectId}/{parentPost}
    defaults: { _controller: "OkulbilisimCmsBundle:Post:create" , object: null, objectId: 0,parentPost: 0}
    requirements: { _method: post }

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "OkulbilisimCmsBundle:Post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "OkulbilisimCmsBundle:Post:update" }
    requirements: { _method: post|put }

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "OkulbilisimCmsBundle:Post:delete" }
    requirements: { _method: post|delete }
