post:
    path:     /
    defaults: { _controller: "OkulbilisimCmsBundle:Post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "OkulbilisimCmsBundle:Post:show" }

post_new:
    path:     /new/{post_type}/{object}/{objectId}/{parentPost}
    defaults: { _controller: "OkulbilisimCmsBundle:Post:new", post_type: 'default', object: null, objectId: 0, parentPost: 0}
post_create:
    path:     /create/{post_type}/{object}/{objectId}/{parentPost}
    defaults: { _controller: "OkulbilisimCmsBundle:Post:create", post_type: 'default', object: null, objectId: 0, parentPost: 0}
    methods:  [POST,PUT]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "OkulbilisimCmsBundle:Post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "OkulbilisimCmsBundle:Post:update" }
    methods:  [POST,PUT]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "OkulbilisimCmsBundle:Post:delete" }